//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM.
        /// </summary>
        public static string AMPeriod {
            get {
                return ResourceManager.GetString("AMPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured when generating the expression description.  Check the cron expression syntax..
        /// </summary>
        public static string AnErrorOccuredWhenGeneratingTheExpressionD {
            get {
                return ResourceManager.GetString("AnErrorOccuredWhenGeneratingTheExpressionD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At.
        /// </summary>
        public static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At .
        /// </summary>
        public static string AtSpace {
            get {
                return ResourceManager.GetString("AtSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at {0}.
        /// </summary>
        public static string AtX0 {
            get {
                return ResourceManager.GetString("AtX0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at {0} minutes past the hour.
        /// </summary>
        public static string AtX0MinutesPastTheHour {
            get {
                return ResourceManager.GetString("AtX0MinutesPastTheHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at {0} seconds past the minute.
        /// </summary>
        public static string AtX0SecondsPastTheMinute {
            get {
                return ResourceManager.GetString("AtX0SecondsPastTheMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to between {0} and {1}.
        /// </summary>
        public static string BetweenX0AndX1 {
            get {
                return ResourceManager.GetString("BetweenX0AndX1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , between day {0} and {1} of the month.
        /// </summary>
        public static string ComaBetweenDayX0AndX1OfTheMonth {
            get {
                return ResourceManager.GetString("ComaBetweenDayX0AndX1OfTheMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , every day.
        /// </summary>
        public static string ComaEveryDay {
            get {
                return ResourceManager.GetString("ComaEveryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , every hour.
        /// </summary>
        public static string ComaEveryHour {
            get {
                return ResourceManager.GetString("ComaEveryHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , every minute.
        /// </summary>
        public static string ComaEveryMinute {
            get {
                return ResourceManager.GetString("ComaEveryMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , every {0} days.
        /// </summary>
        public static string ComaEveryX0Days {
            get {
                return ResourceManager.GetString("ComaEveryX0Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , every {0} days of the week.
        /// </summary>
        public static string ComaEveryX0DaysOfTheWeek {
            get {
                return ResourceManager.GetString("ComaEveryX0DaysOfTheWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , every {0} months.
        /// </summary>
        public static string ComaEveryX0Months {
            get {
                return ResourceManager.GetString("ComaEveryX0Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , every {0} years.
        /// </summary>
        public static string ComaEveryX0Years {
            get {
                return ResourceManager.GetString("ComaEveryX0Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , on day {0} of the month.
        /// </summary>
        public static string ComaOnDayX0OfTheMonth {
            get {
                return ResourceManager.GetString("ComaOnDayX0OfTheMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , only in {0}.
        /// </summary>
        public static string ComaOnlyInX0 {
            get {
                return ResourceManager.GetString("ComaOnlyInX0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , only on {0}.
        /// </summary>
        public static string ComaOnlyOnX0 {
            get {
                return ResourceManager.GetString("ComaOnlyOnX0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , on the .
        /// </summary>
        public static string ComaOnThe {
            get {
                return ResourceManager.GetString("ComaOnThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , on the last day of the month.
        /// </summary>
        public static string ComaOnTheLastDayOfTheMonth {
            get {
                return ResourceManager.GetString("ComaOnTheLastDayOfTheMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , on the last weekday of the month.
        /// </summary>
        public static string ComaOnTheLastWeekdayOfTheMonth {
            get {
                return ResourceManager.GetString("ComaOnTheLastWeekdayOfTheMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , on the last {0} of the month.
        /// </summary>
        public static string ComaOnTheLastX0OfTheMonth {
            get {
                return ResourceManager.GetString("ComaOnTheLastX0OfTheMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , on the {0} of the month.
        /// </summary>
        public static string ComaOnTheX0OfTheMonth {
            get {
                return ResourceManager.GetString("ComaOnTheX0OfTheMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , {0} through {1}.
        /// </summary>
        public static string ComaX0ThroughX1 {
            get {
                return ResourceManager.GetString("ComaX0ThroughX1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , {0} days before the last day of the month.
        /// </summary>
        public static string CommaDaysBeforeTheLastDayOfTheMonth {
            get {
                return ResourceManager.GetString("CommaDaysBeforeTheLastDayOfTheMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , starting {0}.
        /// </summary>
        public static string CommaStartingX0 {
            get {
                return ResourceManager.GetString("CommaStartingX0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every hour.
        /// </summary>
        public static string EveryHour {
            get {
                return ResourceManager.GetString("EveryHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every minute.
        /// </summary>
        public static string EveryMinute {
            get {
                return ResourceManager.GetString("EveryMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every minute between {0} and {1}.
        /// </summary>
        public static string EveryMinuteBetweenX0AndX1 {
            get {
                return ResourceManager.GetString("EveryMinuteBetweenX0AndX1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every second.
        /// </summary>
        public static string EverySecond {
            get {
                return ResourceManager.GetString("EverySecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every {0} hours.
        /// </summary>
        public static string EveryX0Hours {
            get {
                return ResourceManager.GetString("EveryX0Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every {0} minutes.
        /// </summary>
        public static string EveryX0Minutes {
            get {
                return ResourceManager.GetString("EveryX0Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every {0} seconds.
        /// </summary>
        public static string EveryX0Seconds {
            get {
                return ResourceManager.GetString("EveryX0Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fifth.
        /// </summary>
        public static string Fifth {
            get {
                return ResourceManager.GetString("Fifth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first weekday.
        /// </summary>
        public static string FirstWeekday {
            get {
                return ResourceManager.GetString("FirstWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fourth.
        /// </summary>
        public static string Fourth {
            get {
                return ResourceManager.GetString("Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes {0} through {1} past the hour.
        /// </summary>
        public static string MinutesX0ThroughX1PastTheHour {
            get {
                return ResourceManager.GetString("MinutesX0ThroughX1PastTheHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM.
        /// </summary>
        public static string PMPeriod {
            get {
                return ResourceManager.GetString("PMPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds {0} through {1} past the minute.
        /// </summary>
        public static string SecondsX0ThroughX1PastTheMinute {
            get {
                return ResourceManager.GetString("SecondsX0ThroughX1PastTheMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and.
        /// </summary>
        public static string SpaceAnd {
            get {
                return ResourceManager.GetString("SpaceAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and .
        /// </summary>
        public static string SpaceAndSpace {
            get {
                return ResourceManager.GetString("SpaceAndSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} of the month.
        /// </summary>
        public static string SpaceX0OfTheMonth {
            get {
                return ResourceManager.GetString("SpaceX0OfTheMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to third.
        /// </summary>
        public static string Third {
            get {
                return ResourceManager.GetString("Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weekday nearest day {0}.
        /// </summary>
        public static string WeekdayNearestDayX0 {
            get {
                return ResourceManager.GetString("WeekdayNearestDayX0", resourceCulture);
            }
        }
    }
}
